#!/usr/bin/python
#*****************************************************************
# Author: David Bayle
# Contact: contact@davidbayle.com
# This python scripts cheks your ethOS mining rig Hash using Cron.
#
# Usage: If the script detects hashrate lower than your threshold, or crashed GPU(s)
# it will start counting up to 5 (5 x 1 min by defaults) and then force reboot.
#
#
# Settings:
# Do not forget to adjust your global minimum hashrate value by rig [rigMinHashRate] to your needs :
# # rigMinHashRate = 110.0
#
# Requirements:
#
# R1) Create a gpu_crashReboot.log file with 0 as value inside :
# (as ethos user, elevate as root and: )
# # sudo -s
# # echo 0 > /root/gpu_crashReboot.log
#
# R2) Do not forget to setup the cron itself:
# # Cron Check Rig Hash
# * * * * * /usr/bin/python /root/check_rig-hash > /dev/null 2>&1
#
#
# Script will now be allowed to restart your rig if something goes wrong as explained in Usage section.
# Enjoy ;)
#
#

import os
import sys

rigMinHashRate = 110.0
rigRebootLogFile = "/root/gpu_crashReboot.log"
rigStatusLogFile = "/var/run/ethos/status.file"
rigStatsLogFile = "/var/run/ethos/stats.file"


# ================================   functions  =============================
def PrintOutput(dumpStr):
  print dumpStr


def ReadStatusFile():
  try:
    # read rig hash rate from ethos status file
    pStatusLogFile = open(rigStatusLogFile, "r")
    returnedStatus = pStatusLogFile.read()
    return returnedStatus
  except:
    print "File read error in - " + rigStatusLogFile


def WriteRebootCount(count):
  #print count
  try:
    # writes reboot counter in a file
    pLogFile = open(rigRebootLogFile, "w")
    pLogFile.write("%i" % int(count))
    pLogFile.close()
  except:
    print "File write error in - " + rigRebootLogFile


def ReadRebootCount():
  try:
    # read reboot counter from a file
    pLogFile = open(rigRebootLogFile, "r")
    returnedValue = pLogFile.read(1)
#    print returnedValue
    return returnedValue
  except:
    print "File read error in - " + rigRebootLogFile


def IsNumber(n):
    is_number = True
    try:
        num = float(n)
        # check for "nan" floats
        is_number = num == num   # or use `math.isnan(num)`
    except ValueError:
        is_number = False
    return is_number


#================================ RUN ======================================== #

try:
# try reading status file
    rigStats = ReadStatusFile()
# try reading status file
    rigName = ReadRigName()
# gpu reboot count init
    gpuRebootCount = int(ReadRebootCount())
except:
    PrintOutput("UNKNOWN - Invalid Status File / Reboot counter read")

# extract data
try:
    hashRateData =  rigStats.split(" ", 1)
#    print hashRateData[0]
    hashRate = hashRateData[0]
except:
    PrintOutput("UNKNOWN - Invalid RIG Hashrate reading")


if (IsNumber(hashRateData[0])):

  if (float(hashRate) <= float(rigMinHashRate)):
    PrintOutput("WARNING: RIG HASHRATE LOWER THAN THRESHOLD (" + str(rigMinHashRate) + ") : " + hashRate + " (MH/s)")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    sys.exit(STATE_WARNING)
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER CRASHED FOR 5 MINs : RIG HASHRATE LOWER THAN THRESHOLD (" + str(rigMinHashRate) + ") : " + hashRate + " (MH/s)")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")

  else:
    WriteRebootCount(0)
    PrintOutput("OK - [" + str(rigName) + "] Global Rig hashrate : " + hashRate + " (MH/s) [Threshold: " +str(rigMinHashRate) + "]")

else:
  if (hashRateData[0].strip() == "gpu" and hashRateData[1].strip() == "clock problem"):
    PrintOutput("WARNING: A GPU CRASHED !!!")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER GPU CRASHED FOR 5 MINs !!!")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")

  if (hashRateData[0].strip() == "possible" and hashRateData[1].strip() == "miner stall: check miner log"):
    PrintOutput("WARNING: POSSIBLE MINER CRASH !!!")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER GPU CRASHED FOR 5 MINs !!!")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")

  if (hashRateData[0].strip() == "miner" and hashRateData[1].strip() == "started"):
    PrintOutput("WARNING: Miner Starting")
    gpuRebootCount = gpuRebootCount + 1
    WriteRebootCount(int(gpuRebootCount))
    if (gpuRebootCount >= 5):
      PrintOutput("CRITICAL: REBOOTING: MINER DIDN'T START IN 5 MINs !!!")
      WriteRebootCount(0)
      os.system("/opt/ethos/bin/r")

